version: '3'

networks:
  mongonetwork:
    driver: bridge


services:
  db:
    image: mongo
    ports:
      - "3306:3306"
    networks:
      - mongonetwork
    volumes:
      - ./dataset:/dataset

